Fix deletion of files
Add missing parameter to delete() method to prevent crash.

Test case:

$ cat test-02-delete.fastexp
commit refs/heads/master
mark :1
committer Joe Bloggs <joe.bloggs@example.com> 998655365 +0100
data 13
Add file.txt

M 644 inline file.txt
data 21
Contents of file.txt

commit refs/heads/master
mark :2
committer Joe Bloggs <joe.bloggs@example.com> 998844747 +0100
data 16
Remove file.txt

from :1
D file.txt

$ rcs-fast-import -v -v < test-02-delete.fastexp
rcs-fast-import:......(0.00 sec) done.
commit refs/heads/master
rcs-fast-import:    :1 M file.txt
Assigning 1.1 to file.txt
RCS/file.txt,v  <--  file.txt
initial revision: 1.1
done
commit
rcs-fast-import:    :2 D file.txt
Traceback (most recent call last):
  File "./rcs-fast-import", line 815, in <module>
    vcs.delete(op.path)
TypeError: delete() takes at least 3 arguments (2 given)